name: Finalize AI Assets

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  finalize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure files/folders exist
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p .well-known
          if [ ! -f aibom.json ]; then
            printf '%s\n' '{"bomFormat":"AIBOM","specVersion":"1.0","metadata":{"generator":"acreditaia-cli v0.1","timestamp":"'"$(date -u +%Y-%m-%dT%H:%M:%SZ)"'"}}' > aibom.json
          fi

      - name: Compute vars
        id: vars
        shell: bash
        run: |
          owner="${GITHUB_REPOSITORY_OWNER}"
          repo="${GITHUB_REPOSITORY#*/}"
          base_url="https://${owner}.github.io/${repo}"
          ts="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          date_only="$(date -u +'%Y-%m-%d')"
          sha="$(sha256sum aibom.json | awk '{print $1}')"
          {
            echo "owner=${owner}"
            echo "repo=${repo}"
            echo "base_url=${base_url}"
            echo "ts=${ts}"
            echo "date=${date_only}"
            echo "sha=${sha}"
          } >> "$GITHUB_OUTPUT"

      - name: Write /.well-known/ai.txt (no heredoc)
        shell: bash
        run: |
          base='${{ steps.vars.outputs.base_url }}'
          date_only='${{ steps.vars.outputs.date }}'
          printf 'Contact: mailto:acreditaias@gmail.com\n' > .well-known/ai.txt
          printf 'AI-BOM: %s/aibom.json\n' "$base" >> .well-known/ai.txt
          printf 'AI-VC: %s/ai-credential.json\n' "$base" >> .well-known/ai.txt
          printf 'AI-Use: marketing-analytics, soporte-cliente, deteccion-anomalias\n' >> .well-known/ai.txt
          printf 'Provider-GPAI: mistral-large, llama3.1-70b-instruct\n' >> .well-known/ai.txt
          printf 'Last-Updated: %s\n' "$date_only" >> .well-known/ai.txt
          printf 'Policy: %s/ai-policy.html\n' "$base" >> .well-known/ai.txt

      - name: Write ai-credential.json (no heredoc)
        shell: bash
        run: |
          owner='${{ steps.vars.outputs.owner }}'
          repo='${{ steps.vars.outputs.repo }}'
          base='${{ steps.vars.outputs.base_url }}'
          ts='${{ steps.vars.outputs.ts }}'
          sha='${{ steps.vars.outputs.sha }}'
          printf '%s\n' "{
            \"@context\": [\"https://www.w3.org/ns/credentials/v2\"],
            \"type\": [\"VerifiableCredential\",\"AIBOMCredential\"],
            \"issuer\": \"did:web:${owner}.github.io:${repo}\",
            \"issuanceDate\": \"${ts}\",
            \"credentialSubject\": {
              \"id\": \"${base}\",
              \"aibom\": \"${base}/aibom.json\",
              \"bomHash\": \"sha256:${sha}\"
            },
            \"proof\": {
              \"type\": \"DataIntegrityProof\",
              \"cryptosuite\": \"sha256Digest-2023\",
              \"created\": \"${ts}\",
              \"proofValue\": \"sha256:${sha}\",
              \"proofPurpose\": \"assertionMethod\"
            }
          }" > ai-credential.json

      - name: Commit and push
        shell: bash
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .well-known/ai.txt ai-credential.json
          git commit -m "Finalize AI assets" || exit 0
          git push

