name: Finalize AI Assets

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: finalize-ai-assets-${{ github.ref }}
  cancel-in-progress: true

jobs:
  finalize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure folders
        run: |
          set -euo pipefail
          mkdir -p .well-known

      - name: Compute vars
        id: vars
        shell: bash
        run: |
          owner="${GITHUB_REPOSITORY_OWNER}"
          repo="${GITHUB_REPOSITORY#*/}"
          base_url="https://${owner}.github.io/${repo}"
          ts="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          date_only="$(date -u +'%Y-%m-%d')"

          echo "owner=${owner}" >> $GITHUB_OUTPUT
          echo "repo=${repo}" >> $GITHUB_OUTPUT
          echo "base_url=${base_url}" >> $GITHUB_OUTPUT
          echo "ts=${ts}" >> $GITHUB_OUTPUT
          echo "date=${date_only}" >> $GITHUB_OUTPUT

      - name: Create demo AIBOM if missing (idempotent)
        shell: bash
        run: |
          if [ ! -f "aibom.json" ]; then
            cat > aibom.json <<EOF
{
  "bomFormat": "AIBOM",
  "specVersion": "1.0",
  "metadata": {
    "generator": "acreditaia-repo-bootstrap v1",
    "timestamp": "${{ steps.vars.outputs.ts }}",
    "supplier": {
      "name": "AcreditaIA (DEMO)",
      "website": "${{ steps.vars.outputs.base_url }}"
    }
  },
  "aiSystems": [
    {
      "name": "demo-support-bot",
      "purpose": "customer-support",
      "model": "mistral-large",
      "provider": "hosted",
      "inputs": ["texto usuario"],
      "outputs": ["respuesta"],
      "dataSources": ["faq.csv"],
      "promptStores": ["prompts/"],
      "risks": ["alucinaciones"],
      "controls": ["human-in-the-loop"]
    }
  ],
  "dependencies": []
}
EOF
          fi

      - name: Hash AIBOM
        id: hash
        shell: bash
        run: |
          echo "sha=$(sha256sum aibom.json | awk '{print $1}')" >> $GITHUB_OUTPUT

      - name: Create ai-credential.json (demo, idempotent overwrite)
        shell: bash
        run: |
          cat > ai-credential.json <<EOF
{
  "@context": ["https://www.w3.org/ns/credentials/v2"],
  "type": ["VerifiableCredential","AIBOMCredential"],
  "issuer": "did:web:acreditaia.tech",
  "issuanceDate": "${{ steps.vars.outputs.ts }}",
  "credentialSubject": {
    "id": "${{ steps.vars.outputs.base_url }}",
    "aibom": "${{ steps.vars.outputs.base_url }}/aibom.json",
    "bomHash": "sha256:${{ steps.hash.outputs.sha }}"
  },
  "proof": {
    "type": "DataIntegrityProof",
    "cryptosuite": "sha256Digest-2023",
    "created": "${{ steps.vars.outputs.ts }}",
    "proofValue": "sha256:${{ steps.hash.outputs.sha }}",
    "proofPurpose": "assertionMethod"
  }
}
EOF

      - name: Create /.well-known/ai.txt (idempotent overwrite)
        shell: bash
        run: |
          cat > .well-known/ai.txt <<EOF
Contact: mailto:acreditaias@gmail.com
AI-BOM: ${{ steps.vars.outputs.base_url }}/aibom.json
AI-VC:  ${{ steps.vars.outputs.base_url }}/ai-credential.json
AI-Use: soporte-cliente
Provider-GPAI: mistral-large
Last-Updated: ${{ steps.vars.outputs.date }}
Policy: ${{ steps.vars.outputs.base_url }}/ai-policy.html
EOF

      - name: Ensure policy/model/risk exist (demo, if missing)
        shell: bash
        run: |
          [ -f ai-policy.html ] || echo "<!doctype html><meta charset='utf-8'><title>Política IA (demo)</title><h1>Política IA (demo)</h1><p>Ámbitos: soporte-cliente.</p>" > ai-policy.html
          [ -f MODEL_CARD.md ] || echo "# Model Card (demo)\n\n## demo-support-bot\n- Propósito: soporte.\n- Riesgos: alucinaciones.\n- Controles: HITL.\n" > MODEL_CARD.md
          [ -f risk_register.csv ] || echo "riesgo,severidad,probabilidad,control,evidencia\nalucinaciones,media,media,human-in-the-loop,MODEL_CARD.md#demo-support-bot" > risk_register.csv

      - name: Commit & push
        shell: bash
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .well-known/ai.txt aibom.json ai-credential.json ai-policy.html MODEL_CARD.md risk_register.csv
          git commit -m "Finalize AI assets (demo)" || exit 0
          git push
